name: la_fuite
favicon: null
layout_spectrum: 0.3166
typography_spectrum: 0.57887
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4467a3'
    - '#7b9fc2'
    - '#646d69'
    - '#475153'
    - '#77807c'
  brandStrength: 0.4375
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 0.8059819226618856
purpose: []
