name: la_fuite
favicon: null
layout_spectrum: 0.8046364232432097
typography_spectrum: 0.03689945419318974
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4204278076067567
  lightness: 0.44390641478821635
  saturation: 0.3819167693145573
  rhythmicContrast: 0.8059819226618856
purpose: []
